package com.bs.competition.entity.simple;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String mobliephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.id
	 * @return  the value of admin.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.id
	 * @param id  the value for admin.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.name
	 * @return  the value of admin.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.name
	 * @param name  the value for admin.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.sex
	 * @return  the value of admin.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.sex
	 * @param sex  the value for admin.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.mobliephone
	 * @return  the value of admin.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getMobliephone() {
		return mobliephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.mobliephone
	 * @param mobliephone  the value for admin.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setMobliephone(String mobliephone) {
		this.mobliephone = mobliephone == null ? null : mobliephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.userid
	 * @return  the value of admin.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.userid
	 * @param userid  the value for admin.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.status
	 * @return  the value of admin.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.status
	 * @param status  the value for admin.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.addtime
	 * @return  the value of admin.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.addtime
	 * @param addtime  the value for admin.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.imageid
	 * @return  the value of admin.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.imageid
	 * @param imageid  the value for admin.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setImageid(String imageid) {
		this.imageid = imageid == null ? null : imageid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.remark
	 * @return  the value of admin.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.remark
	 * @param remark  the value for admin.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}