package com.bs.competition.entity.simple;

public class Image {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private byte[] content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.id
	 * @return  the value of image.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.id
	 * @param id  the value for image.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.name
	 * @return  the value of image.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.name
	 * @param name  the value for image.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.content
	 * @return  the value of image.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public byte[] getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.content
	 * @param content  the value for image.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setContent(byte[] content) {
		this.content = content;
	}
}