package com.bs.competition.entity.simple;

public class News {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.title
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.type
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.sysstatus
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer sysstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String pubid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.id
	 * @return  the value of news.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.id
	 * @param id  the value for news.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.title
	 * @return  the value of news.title
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.title
	 * @param title  the value for news.title
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.content
	 * @return  the value of news.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.content
	 * @param content  the value for news.content
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.addtime
	 * @return  the value of news.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.addtime
	 * @param addtime  the value for news.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.imageid
	 * @return  the value of news.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.imageid
	 * @param imageid  the value for news.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setImageid(String imageid) {
		this.imageid = imageid == null ? null : imageid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.type
	 * @return  the value of news.type
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.type
	 * @param type  the value for news.type
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.sysstatus
	 * @return  the value of news.sysstatus
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getSysstatus() {
		return sysstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.sysstatus
	 * @param sysstatus  the value for news.sysstatus
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setSysstatus(Integer sysstatus) {
		this.sysstatus = sysstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.pubid
	 * @return  the value of news.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getPubid() {
		return pubid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.pubid
	 * @param pubid  the value for news.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setPubid(String pubid) {
		this.pubid = pubid == null ? null : pubid.trim();
	}
}