package com.bs.competition.entity.simple;

public class School {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column school.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column school.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column school.id
	 * @return  the value of school.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column school.id
	 * @param id  the value for school.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column school.name
	 * @return  the value of school.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column school.name
	 * @param name  the value for school.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}