package com.bs.competition.entity.simple;

public class Score {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.id
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.studentid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private String studentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.teacherid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private String teacherid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.addtime
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.newscore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private Integer newscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.prascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private Integer prascore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column score.feascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	private Integer feascore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.id
	 * @return  the value of score.id
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.id
	 * @param id  the value for score.id
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.studentid
	 * @return  the value of score.studentid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public String getStudentid() {
		return studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.studentid
	 * @param studentid  the value for score.studentid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setStudentid(String studentid) {
		this.studentid = studentid == null ? null : studentid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.teacherid
	 * @return  the value of score.teacherid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public String getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.teacherid
	 * @param teacherid  the value for score.teacherid
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setTeacherid(String teacherid) {
		this.teacherid = teacherid == null ? null : teacherid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.addtime
	 * @return  the value of score.addtime
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.addtime
	 * @param addtime  the value for score.addtime
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.newscore
	 * @return  the value of score.newscore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public Integer getNewscore() {
		return newscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.newscore
	 * @param newscore  the value for score.newscore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setNewscore(Integer newscore) {
		this.newscore = newscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.prascore
	 * @return  the value of score.prascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public Integer getPrascore() {
		return prascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.prascore
	 * @param prascore  the value for score.prascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setPrascore(Integer prascore) {
		this.prascore = prascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column score.feascore
	 * @return  the value of score.feascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public Integer getFeascore() {
		return feascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column score.feascore
	 * @param feascore  the value for score.feascore
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	public void setFeascore(Integer feascore) {
		this.feascore = feascore;
	}
}