package com.bs.competition.entity.simple;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.id
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.name
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.sex
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.schoolid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String schoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.mobliephone
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String mobliephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.status
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.userid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.score
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.newscore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer newscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.prascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer prascore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.feascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer feascore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.isapply
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Integer isapply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.addtime
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.imageid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.remark
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.id
	 * @return  the value of student.id
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.id
	 * @param id  the value for student.id
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.name
	 * @return  the value of student.name
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.name
	 * @param name  the value for student.name
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.sex
	 * @return  the value of student.sex
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.sex
	 * @param sex  the value for student.sex
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.schoolid
	 * @return  the value of student.schoolid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getSchoolid() {
		return schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.schoolid
	 * @param schoolid  the value for student.schoolid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setSchoolid(String schoolid) {
		this.schoolid = schoolid == null ? null : schoolid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.mobliephone
	 * @return  the value of student.mobliephone
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getMobliephone() {
		return mobliephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.mobliephone
	 * @param mobliephone  the value for student.mobliephone
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setMobliephone(String mobliephone) {
		this.mobliephone = mobliephone == null ? null : mobliephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.status
	 * @return  the value of student.status
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.status
	 * @param status  the value for student.status
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.userid
	 * @return  the value of student.userid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.userid
	 * @param userid  the value for student.userid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.score
	 * @return  the value of student.score
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.score
	 * @param score  the value for student.score
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.newscore
	 * @return  the value of student.newscore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getNewscore() {
		return newscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.newscore
	 * @param newscore  the value for student.newscore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setNewscore(Integer newscore) {
		this.newscore = newscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.prascore
	 * @return  the value of student.prascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getPrascore() {
		return prascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.prascore
	 * @param prascore  the value for student.prascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setPrascore(Integer prascore) {
		this.prascore = prascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.feascore
	 * @return  the value of student.feascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getFeascore() {
		return feascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.feascore
	 * @param feascore  the value for student.feascore
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setFeascore(Integer feascore) {
		this.feascore = feascore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.isapply
	 * @return  the value of student.isapply
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Integer getIsapply() {
		return isapply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.isapply
	 * @param isapply  the value for student.isapply
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setIsapply(Integer isapply) {
		this.isapply = isapply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.addtime
	 * @return  the value of student.addtime
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.addtime
	 * @param addtime  the value for student.addtime
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.imageid
	 * @return  the value of student.imageid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.imageid
	 * @param imageid  the value for student.imageid
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setImageid(String imageid) {
		this.imageid = imageid == null ? null : imageid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.remark
	 * @return  the value of student.remark
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.remark
	 * @param remark  the value for student.remark
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}