package com.bs.competition.entity.simple;

public class Teacher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.schoolid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String schoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String mobliephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.groups
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private Integer groups;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String pubid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.id
	 * @return  the value of teacher.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.id
	 * @param id  the value for teacher.id
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.name
	 * @return  the value of teacher.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.name
	 * @param name  the value for teacher.name
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.sex
	 * @return  the value of teacher.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.sex
	 * @param sex  the value for teacher.sex
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.schoolid
	 * @return  the value of teacher.schoolid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getSchoolid() {
		return schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.schoolid
	 * @param schoolid  the value for teacher.schoolid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setSchoolid(String schoolid) {
		this.schoolid = schoolid == null ? null : schoolid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.mobliephone
	 * @return  the value of teacher.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getMobliephone() {
		return mobliephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.mobliephone
	 * @param mobliephone  the value for teacher.mobliephone
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setMobliephone(String mobliephone) {
		this.mobliephone = mobliephone == null ? null : mobliephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.status
	 * @return  the value of teacher.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.status
	 * @param status  the value for teacher.status
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.userid
	 * @return  the value of teacher.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.userid
	 * @param userid  the value for teacher.userid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.addtime
	 * @return  the value of teacher.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.addtime
	 * @param addtime  the value for teacher.addtime
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.groups
	 * @return  the value of teacher.groups
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Integer getGroups() {
		return groups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.groups
	 * @param groups  the value for teacher.groups
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setGroups(Integer groups) {
		this.groups = groups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.pubid
	 * @return  the value of teacher.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getPubid() {
		return pubid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.pubid
	 * @param pubid  the value for teacher.pubid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setPubid(String pubid) {
		this.pubid = pubid == null ? null : pubid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.imageid
	 * @return  the value of teacher.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.imageid
	 * @param imageid  the value for teacher.imageid
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setImageid(String imageid) {
		this.imageid = imageid == null ? null : imageid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.remark
	 * @return  the value of teacher.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.remark
	 * @param remark  the value for teacher.remark
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}