package com.bs.competition.entity.simple;

import java.util.ArrayList;
import java.util.List;

public class TeacherExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public TeacherExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSchoolidIsNull() {
			addCriterion("schoolid is null");
			return (Criteria) this;
		}

		public Criteria andSchoolidIsNotNull() {
			addCriterion("schoolid is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolidEqualTo(String value) {
			addCriterion("schoolid =", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidNotEqualTo(String value) {
			addCriterion("schoolid <>", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidGreaterThan(String value) {
			addCriterion("schoolid >", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidGreaterThanOrEqualTo(String value) {
			addCriterion("schoolid >=", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidLessThan(String value) {
			addCriterion("schoolid <", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidLessThanOrEqualTo(String value) {
			addCriterion("schoolid <=", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidLike(String value) {
			addCriterion("schoolid like", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidNotLike(String value) {
			addCriterion("schoolid not like", value, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidIn(List<String> values) {
			addCriterion("schoolid in", values, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidNotIn(List<String> values) {
			addCriterion("schoolid not in", values, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidBetween(String value1, String value2) {
			addCriterion("schoolid between", value1, value2, "schoolid");
			return (Criteria) this;
		}

		public Criteria andSchoolidNotBetween(String value1, String value2) {
			addCriterion("schoolid not between", value1, value2, "schoolid");
			return (Criteria) this;
		}

		public Criteria andMobliephoneIsNull() {
			addCriterion("mobliephone is null");
			return (Criteria) this;
		}

		public Criteria andMobliephoneIsNotNull() {
			addCriterion("mobliephone is not null");
			return (Criteria) this;
		}

		public Criteria andMobliephoneEqualTo(String value) {
			addCriterion("mobliephone =", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneNotEqualTo(String value) {
			addCriterion("mobliephone <>", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneGreaterThan(String value) {
			addCriterion("mobliephone >", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneGreaterThanOrEqualTo(String value) {
			addCriterion("mobliephone >=", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneLessThan(String value) {
			addCriterion("mobliephone <", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneLessThanOrEqualTo(String value) {
			addCriterion("mobliephone <=", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneLike(String value) {
			addCriterion("mobliephone like", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneNotLike(String value) {
			addCriterion("mobliephone not like", value, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneIn(List<String> values) {
			addCriterion("mobliephone in", values, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneNotIn(List<String> values) {
			addCriterion("mobliephone not in", values, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneBetween(String value1, String value2) {
			addCriterion("mobliephone between", value1, value2, "mobliephone");
			return (Criteria) this;
		}

		public Criteria andMobliephoneNotBetween(String value1, String value2) {
			addCriterion("mobliephone not between", value1, value2,
					"mobliephone");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userid like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userid not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Long value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Long value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Long value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Long value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Long value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Long value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Long> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Long> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Long value1, Long value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Long value1, Long value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andGroupsIsNull() {
			addCriterion("groups is null");
			return (Criteria) this;
		}

		public Criteria andGroupsIsNotNull() {
			addCriterion("groups is not null");
			return (Criteria) this;
		}

		public Criteria andGroupsEqualTo(Integer value) {
			addCriterion("groups =", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsNotEqualTo(Integer value) {
			addCriterion("groups <>", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsGreaterThan(Integer value) {
			addCriterion("groups >", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsGreaterThanOrEqualTo(Integer value) {
			addCriterion("groups >=", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsLessThan(Integer value) {
			addCriterion("groups <", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsLessThanOrEqualTo(Integer value) {
			addCriterion("groups <=", value, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsIn(List<Integer> values) {
			addCriterion("groups in", values, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsNotIn(List<Integer> values) {
			addCriterion("groups not in", values, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsBetween(Integer value1, Integer value2) {
			addCriterion("groups between", value1, value2, "groups");
			return (Criteria) this;
		}

		public Criteria andGroupsNotBetween(Integer value1, Integer value2) {
			addCriterion("groups not between", value1, value2, "groups");
			return (Criteria) this;
		}

		public Criteria andPubidIsNull() {
			addCriterion("pubid is null");
			return (Criteria) this;
		}

		public Criteria andPubidIsNotNull() {
			addCriterion("pubid is not null");
			return (Criteria) this;
		}

		public Criteria andPubidEqualTo(String value) {
			addCriterion("pubid =", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidNotEqualTo(String value) {
			addCriterion("pubid <>", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidGreaterThan(String value) {
			addCriterion("pubid >", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidGreaterThanOrEqualTo(String value) {
			addCriterion("pubid >=", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidLessThan(String value) {
			addCriterion("pubid <", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidLessThanOrEqualTo(String value) {
			addCriterion("pubid <=", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidLike(String value) {
			addCriterion("pubid like", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidNotLike(String value) {
			addCriterion("pubid not like", value, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidIn(List<String> values) {
			addCriterion("pubid in", values, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidNotIn(List<String> values) {
			addCriterion("pubid not in", values, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidBetween(String value1, String value2) {
			addCriterion("pubid between", value1, value2, "pubid");
			return (Criteria) this;
		}

		public Criteria andPubidNotBetween(String value1, String value2) {
			addCriterion("pubid not between", value1, value2, "pubid");
			return (Criteria) this;
		}

		public Criteria andImageidIsNull() {
			addCriterion("imageid is null");
			return (Criteria) this;
		}

		public Criteria andImageidIsNotNull() {
			addCriterion("imageid is not null");
			return (Criteria) this;
		}

		public Criteria andImageidEqualTo(String value) {
			addCriterion("imageid =", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotEqualTo(String value) {
			addCriterion("imageid <>", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidGreaterThan(String value) {
			addCriterion("imageid >", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidGreaterThanOrEqualTo(String value) {
			addCriterion("imageid >=", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidLessThan(String value) {
			addCriterion("imageid <", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidLessThanOrEqualTo(String value) {
			addCriterion("imageid <=", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidLike(String value) {
			addCriterion("imageid like", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotLike(String value) {
			addCriterion("imageid not like", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidIn(List<String> values) {
			addCriterion("imageid in", values, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotIn(List<String> values) {
			addCriterion("imageid not in", values, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidBetween(String value1, String value2) {
			addCriterion("imageid between", value1, value2, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotBetween(String value1, String value2) {
			addCriterion("imageid not between", value1, value2, "imageid");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table teacher
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 28 21:11:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
    
    
    /** paging param start */
	protected Integer start;
	/** paging param end */
	protected Integer end;

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

}