package com.bs.competition.dao.inf;

import com.bs.competition.entity.simple.Image;
import com.bs.competition.entity.simple.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int countByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insert(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insertSelective(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	List<Image> selectByExampleWithBLOBs(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	List<Image> selectByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	Image selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Image record,
			@Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Image record,
			@Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExample(@Param("record") Image record,
			@Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKeySelective(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKey(Image record);
}