package com.bs.competition.dao.inf;

import com.bs.competition.entity.simple.News;
import com.bs.competition.entity.simple.NewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int countByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insert(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insertSelective(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	List<News> selectByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	News selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") News record,
			@Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExample(@Param("record") News record,
			@Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKeySelective(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKey(News record);

	public List<News> selectByExamplePaging(NewsExample example);
}