package com.bs.competition.dao.inf;

import com.bs.competition.entity.simple.School;
import com.bs.competition.entity.simple.SchoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int countByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insert(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int insertSelective(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	List<School> selectByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	School selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") School record,
			@Param("example") SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByExample(@Param("record") School record,
			@Param("example") SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKeySelective(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school
	 * @mbggenerated  Sun Apr 10 10:52:06 CST 2017
	 */
	int updateByPrimaryKey(School record);
}