package com.bs.competition.dao.inf;

import com.bs.competition.entity.simple.Score;
import com.bs.competition.entity.simple.ScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int countByExample(ScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int deleteByExample(ScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int insert(Score record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int insertSelective(Score record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	List<Score> selectByExample(ScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	Score selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Score record,
			@Param("example") ScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int updateByExample(@Param("record") Score record,
			@Param("example") ScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int updateByPrimaryKeySelective(Score record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table score
	 * @mbggenerated  Wed Apr 13 14:31:55 CST 2017
	 */
	int updateByPrimaryKey(Score record);
}