package com.bs.competition.dao.inf;

import com.bs.competition.entity.simple.Student;
import com.bs.competition.entity.simple.StudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int countByExample(StudentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int deleteByExample(StudentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int insert(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int insertSelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	List<Student> selectByExample(StudentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	Student selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Student record,
			@Param("example") StudentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int updateByExample(@Param("record") Student record,
			@Param("example") StudentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int updateByPrimaryKeySelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Fri Apr 15 11:14:48 CST 2017
	 */
	int updateByPrimaryKey(Student record);

	public List<Student> selectByExamplePaging(StudentExample example);
}